### ISSUE TITLE
Height issue

### ISSUE THREAD

**Issue by jockeeskis** [vue-a11y/vue-focus-loop#6]
Would be nice to be able to style this div

![image](https://user-images.githubusercontent.com/21436739/110481441-dd16ed00-80e7-11eb-93fa-ff5f23e05969.png)

Its causing alot of height issues for some modals. Or it should atleast always be height: 100% or something like that

**Comment by ktquez** [comment]
Hi @jockeeskis 

You can use like this:

```css
.vue-focus-loop > div:nth-child(2) {
  height: 100%;
}
```
